#ifndef UI_GAME_TYPES_HPP
#define UI_GAME_TYPES_HPP

enum SCRIPTEVENT {
    // TODO
    SCRIPT_UNIT_TARGET = 12,
    SCRIPT_UNIT_DISPLAYPOWER = 17,
    SCRIPT_UNIT_HEALTH = 18,
    SCRIPT_UNIT_MANA = 19,
    SCRIPT_UNIT_MAXHEALTH = 26,
    SCRIPT_UNIT_MAXMANA = 27,
    SCRIPT_UNIT_LEVEL = 48,
    SCRIPT_UNIT_FACTION = 49,
    SCRIPT_UNIT_MODEL_CHANGED = 146,
    SCRIPT_PLAYER_XP_UPDATE = 151,
    SCRIPT_PLAYER_TARGET_CHANGED = 157,
    SCRIPT_PLAYER_MONEY = 163,
    // TODO
    SCRIPT_ACTIONBAR_PAGE_CHANGED = 175,
    SCRIPT_ACTIONBAR_SLOT_CHANGED = 176,
    // TODO
    SCRIPT_PLAYER_LOGIN = 253,
    SCRIPT_PLAYER_LOGOUT = 254,
    SCRIPT_PLAYER_ENTERING_WORLD = 255,
    // TODO
    SCRIPT_CVAR_UPDATE = 298,
    // TODO
};

enum CAMERA_VIEW {
    VIEW_FIRST_PERSON       = 0,
    VIEW_THIRD_PERSON_A     = 1,
    VIEW_THIRD_PERSON_B     = 2,
    VIEW_THIRD_PERSON_C     = 3,
    VIEW_THIRD_PERSON_D     = 4,
    VIEW_THIRD_PERSON_E     = 5,
    VIEW_COMMENTATOR        = 6,
    VIEW_BARBER_SHOP        = 7,
    MAX_CAMERA_VIEWS,
};

#endif
