#!/usr/bin/env python3
"""Compile the D3D9 HLSL under src/world/shaders into an embedded C array header.

The reference ships its shaders in MPQ archives, so whoa carries its own bytecode compiled at
build-authoring time rather than at runtime. Each source names its profile in a leading comment:

    // profile: vs_2_0
    // symbol:  g_terrainVsD3d9

Run it after editing any .hlsl and commit the regenerated header.
"""

import os
import re
import subprocess
import sys

FXC = r"C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64\fxc.exe"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src", "world", "shaders")


def compile_one(path):
    text = open(path, encoding="utf-8").read()
    profile = re.search(r"//\s*profile:\s*(\S+)", text)
    symbol = re.search(r"//\s*symbol:\s*(\S+)", text)

    if not profile or not symbol:
        sys.exit("%s: needs a '// profile:' and a '// symbol:' comment" % path)

    out = path + ".bin"
    cmd = [FXC, "/T", profile.group(1), "/E", "main", "/Fo", out, "/O3", "/nologo", path]
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        sys.exit("%s:\n%s%s" % (path, result.stdout, result.stderr))

    data = open(out, "rb").read()
    os.remove(out)
    return symbol.group(1), data


def emit(symbol, data):
    lines = ["static const unsigned char %s[] = {" % symbol]

    for i in range(0, len(data), 12):
        chunk = ", ".join("0x%02x" % b for b in data[i:i + 12])
        lines.append("    %s," % chunk)

    lines.append("};")
    return "\n".join(lines)


def main():
    targets = sys.argv[1:]

    if not targets:
        sys.exit("usage: compile-shaders.py <header> <source.hlsl>...")

    header = targets[0]
    guard = os.path.basename(header).upper().replace(".", "_").replace("-", "_")
    parts = [
        "#ifndef %s" % guard,
        "#define %s" % guard,
        "// Auto-generated by tools/compile-shaders.py. Do not edit; edit the .hlsl and re-run.",
        "",
    ]

    for path in targets[1:]:
        symbol, data = compile_one(path)
        parts.append("// %s (%d bytes)" % (os.path.basename(path), len(data)))
        parts.append(emit(symbol, data))
        parts.append("")
        print("%-24s -> %-28s %5d bytes" % (os.path.basename(path), symbol, len(data)))

    parts.append("#endif")
    open(header, "w", encoding="utf-8", newline="\n").write("\n".join(parts) + "\n")
    print("wrote %s" % header)


if __name__ == "__main__":
    main()
